In [19]:
import nibabel as nib
from os.path import join as opj
import numpy as np

In [22]:
data="/projects/datasets/iseg2019"
train=opj(data, "iSeg-2019-Training")
val=opj(data, "iSeg-2019-Validation") # does not have label files
out=opj(data, "iSeg-2019-nifti")

In [25]:
sbj1 = nib.load(opj(train, "subject-1-T1.img"))

In [30]:
for i in range(11, 23):
    # load image
    for imgtyp in ["T1", "T2", "label"]:
        sbj = f"subject-{i}-{imgtyp}"
        print(f"Working on {sbj}")
        img = nib.load(opj(val, sbj + ".img"))
        img_array = np.asanyarray(img.dataobj)

        # save as nifti
        mgh_img = nib.MGHImage(np.squeeze(img_array), img.affine, img.header)
        nib.save(mgh_img, opj(out, sbj + '.mgz'))

Working on subject-11-T1
Working on subject-11-T2
Working on subject-11-label


FileNotFoundError: No such file or no access: '/projects/datasets/iseg2019/iSeg-2019-Validation/subject-11-label.img'

In [12]:
sbj2 = nib.load(opj(out, "subject-1-T1.nii.gz"))

In [26]:
print(sbj1.header)

<class 'nibabel.spm2analyze.Spm2AnalyzeHeader'> object, endian='<'
sizeof_hdr     : 348
data_type      : b'SHORT'
db_name        : b''
extents        : 16384
session_error  : 0
regular        : b'r'
hkey_un0       : b''
dim            : [  4 144 192 256   1   1   1   1]
vox_units      : b''
cal_units      : b''
unused1        : 0
datatype       : int16
bitpix         : 16
dim_un0        : 0
pixdim         : [0. 1. 1. 1. 1. 1. 1. 1.]
vox_offset     : 0.0
scl_slope      : nan
scl_inter      : 0.0
funused3       : 0.0
cal_max        : 0.0
cal_min        : 0.0
compressed     : 0
verified       : 0
glmax          : 0
glmin          : 0
descrip        : b''
aux_file       : b''
orient         : b''
origin         : [0 0 0 0 0]
generated      : b''
scannum        : b''
patient_id     : b''
exp_date       : b''
exp_time       : b''
hist_un0       : b''
views          : 0
vols_added     : 0
start_field    : 0
field_skip     : 0
omax           : 0
omin           : 0
smax           : 0
smin      

In [17]:
hdr = nib.load(opj(train, "subject-1-T1.hdr"))
print(hdr)

<class 'nibabel.spm2analyze.Spm2AnalyzeImage'>
data shape (144, 192, 256, 1)
affine: 
[[  -1.     0.     0.    71.5]
 [   0.     1.     0.   -95.5]
 [   0.     0.     1.  -127.5]
 [   0.     0.     0.     1. ]]
metadata:
<class 'nibabel.spm2analyze.Spm2AnalyzeHeader'> object, endian='<'
sizeof_hdr     : 348
data_type      : b'SHORT'
db_name        : b''
extents        : 16384
session_error  : 0
regular        : b'r'
hkey_un0       : b''
dim            : [  4 144 192 256   1   1   1   1]
vox_units      : b''
cal_units      : b''
unused1        : 0
datatype       : int16
bitpix         : 16
dim_un0        : 0
pixdim         : [0. 1. 1. 1. 1. 1. 1. 1.]
vox_offset     : 0.0
scl_slope      : nan
scl_inter      : 0.0
funused3       : 0.0
cal_max        : 0.0
cal_min        : 0.0
compressed     : 0
verified       : 0
glmax          : 0
glmin          : 0
descrip        : b''
aux_file       : b''
orient         : b''
origin         : [0 0 0 0 0]
generated      : b''
scannum        : b''
patien